### ISSUE TITLE
problem with wigle lookup on the server

### ISSUE THREAD

**Issue by localtracker** [hubert3/iSniff-GPS#16]
Everything seems to work fine in case of capturing and displaying the data in the console and the web interface with the sqlite db but trying to lookup the ssid via the web interface crashes the web page. Also the apple wifi lookup does not load the map and theres only a location pointer on an empty background visible.

**Comment by localtracker** [comment]
nevermind, found the issue, had to update the cookie in the wigle conf file.

**Comment by hubert3** [comment]
Apple WiFi Geolocation should also work, the default URL /isniff-gps/apple-wloc/00:1e:52:7a:ae:ad works for me

To locate another BSSID (router MAC address), just change the URL

**Comment by tjt263** [comment]
thanks, this is a very i interesting project. can you give a syntax example?

**Comment by localtracker** [comment]
ok hubert, i'll try the apple lookup once again and let you know.. btw, its an awesome piece of software!
