### ISSUE TITLE
Google Maps not displaying via apple-mobil or apple-mobil-lte

### ISSUE THREAD

**Issue by blackdog07** [hubert3/iSniff-GPS#18]
I've been trying to locate a mobile device via the "Apple LTE Geolocation" and the "Apple GSM/3G Geolocation" link. The default url works and displays a map but when I try to find a different device by changing the url, I get a red icon as if it locates the device but no map. I use a url with the following format:
http://<myserver>:8000/apple-mobile/MCC:MNC:LAC:CID.
If I put in some bogus phone number, I get 0 results found message so I think it is finding it, but I can;t tell where :-(
Any suggestions?

**Comment by blackdog07** [comment]
So I lookup on OpenCellID and find a tower in my area and get the MCC, MNC,LAC and CID then enter them in the url like http://127.0.0.1:8000http:/apple-mobile/MCC:MNC:LAC:CID and get just the red dot. Checking further it seems the wloc.py - r = requests.post('https://gs-loc.apple.com/clls/wloc',headers=headers,data=data,verify=False) returns only a <Response [200]> and no data. 
Anyway, I am trying to learn about GSM and I probably don't understand how ths is supposed to work.

**Comment by hubert3** [comment]
Hi, the /apple-mobile page allows you to query Apple's database of cell tower locations and display them on a map. This data is used by iPhones to locate themselves.

MCC (Mobile Country Code)
MNC (Mobile Network Code)
LAC (Location Area Code)
CID (Cell ID)

You can't use this to query the location of a particular phone, only to see the location of particular cell IDs (and others in the local area).
