### ISSUE TITLE
BSSID not populating

### ISSUE THREAD

**Issue by blackdog07** [hubert3/iSniff-GPS#19]
I assume the BSSID should be populating but it doesn't seem to work for me. It would be really nice to be able to click on a BSSID and have it take you to the "Apple WiFi Geolocation" and populate the url with the BSSID you are interested in. I can manually put a BSSID in the url and it works fine though. It is just that the BSSID's are not being populated in the UI. I know that the mon interface can see the AP because it is setting right next to me and I can see it via a second mon interface or if I stop iSniff and airodump-ng on the same mon interface that I use for iSniff.

**Comment by hubert3** [comment]
Hi, the "Apple Wifi Geolocation" view only shows data returned from Apple Location Services. It is not supposed to display any BSSIDs or other data that you captured.

Information you captured only shows up on the Clients, Networks and Stats pages. All the Apple* pages show purely information returned by Apple's APIs.
